version: 0.0
Resources:
  - test: # Replace "MyFunction" with the name of your Lambda function
      Type: AWS::Lambda::http
      Properties:
        Name: "http" # Specify the name of your Lambda function
        Alias: "beta" # Specify the alias for your Lambda function
        CurrentVersion: "1" # Specify the current version of your Lambda function
        TargetVersion: "2" # Specify the version of your Lambda function to deploy
